GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"theseasedas",
    "author": "12345123",
    "url": "bla bla blaasdasda",
    "likes": 12
}